name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: wNe2SJytpEPUblyKwhNwZqnOVhdYYhD7:61e739880a997a84b946cf01
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './swagger/swagger.yaml'
          # api-version: 'v1.0.0'
